# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('brief', models.CharField(default='', max_length=200)),
                ('Category', models.CharField(choices=[('L', 'Logo'), ('C', 'Clothing'), ('W', 'WebApp'), ('A', 'Advertising'), ('I', 'Illistration'), ('P', 'Packaging')], default='S', max_length=1)),
                ('use', models.CharField(default='', max_length=50)),
                ('when', models.CharField(choices=[('A', 'ASAP'), ('W', '1 Week'), ('F', '2 Weeks'), ('M', '4 weeks +')], default='S', max_length=1)),
                ('inspiration', models.URLField(default='', max_length=100)),
                ('draft', models.ImageField(blank=True, null=True, upload_to='img/draft')),
            ],
        ),
    ]
