# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Category',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Logo', 'Logo'), ('Clothing', 'Clothing'), ('WebApp', 'WebApp'), ('Advertising', 'Advertising'), ('Illistration', 'Illistration'), ('Packaging', 'Packaging')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='when',
            field=models.CharField(choices=[('ASAP', 'ASAP'), ('1 week', '1 Week'), ('2 weeks', '2 Weeks'), ('4 weeks+', '4 weeks+')], default='', max_length=50),
        ),
    ]
