# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_work', '0002_auto_20200209_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('25', 'Logo'), ('20', 'Clothing'), ('30', 'WebApp'), ('35', 'Advertising'), ('40', 'Illistration'), ('15', 'Packaging')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='when',
            field=models.CharField(choices=[('50', 'ASAP'), ('40', '1 Week'), ('30', '2 Weeks'), ('20', '4 weeks+')], default='', max_length=50),
        ),
    ]
