# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_work', '0007_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user_name',
        ),
    ]
