# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-19 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='current_date',
            new_name='request_date',
        ),
    ]
