# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200219_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_line_item',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='purchase_line_item',
            name='work',
        ),
        migrations.DeleteModel(
            name='purchase',
        ),
        migrations.DeleteModel(
            name='purchase_line_item',
        ),
    ]
