# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_auto_20200224_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(default='', max_length=50)),
                ('customer_email', models.CharField(default='', max_length=50)),
                ('customer_number', models.IntegerField(default='')),
            ],
        ),
    ]
