# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_customer_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_info',
        ),
    ]
