# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unpurchasable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('brief', models.CharField(default='', max_length=200)),
                ('piece_category', models.CharField(choices=[('25', 'Logo'), ('20', 'Clothing'), ('30', 'WebApp'), ('35', 'Advertising'), ('40', 'Illistration'), ('15', 'Packaging')], default='', max_length=50)),
                ('use', models.CharField(default='', max_length=50)),
                ('where', models.URLField(default='', max_length=100)),
                ('piece', models.ImageField(blank=True, null=True, upload_to='piece_img')),
            ],
        ),
        migrations.DeleteModel(
            name='filter_piece',
        ),
    ]
