# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-28 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unpurchasable', '0002_auto_20200227_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit_piece',
        ),
    ]
