# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-28 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
    ]
